import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.amazon.com/');
  await page.getByRole('textbox', { name: 'Search For' }).click();
  await page.getByRole('textbox', { name: 'Search For' }).click();
  await page.getByRole('textbox', { name: 'Search For' }).fill('iphone');
  await page.getByRole('textbox', { name: 'Search For' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search For' }).click();
  await page.getByRole('textbox', { name: 'Search For' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search For' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search For' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search For' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search For' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search For' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search For' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search For' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search For' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search For' }).press('Enter');
  await page.getByRole('button', { name: 'Go' }).click();
  await page.getByRole('list', { name: 'Condition' }).click();
  await page.getByRole('link', { name: '$300 to $' }).click();
  await page.getByRole('link', { name: '$35 to $' }).click();
  await page.getByRole('link', { name: 'Apply Samsung filter to' }).click();
  await page.getByRole('link', { name: 'Apply Verizon Wireless filter' }).click();
  await page.locator('.s-widget-container.s-spacing-small.s-widget-container-height-small.celwidget.slot\\=MAIN.template\\=SEARCH_RESULTS.widgetId\\=search-results_2 > span > .puis-card-container > div > div > .puisg-col.puisg-col-4-of-4.puisg-col-4-of-8.puisg-col-4-of-12.puisg-col-4-of-16.puisg-col-4-of-20.puisg-col-4-of-24.puis-list-col-left > .puisg-col-inner > .s-product-image-container > div > .rush-component > .a-link-normal').click();
  await page.getByRole('link', { name: 'Add to List' }).click();
  await page.getByRole('textbox', { name: 'Enter your mobile number or' }).click();
  await page.getByRole('textbox', { name: 'Enter your mobile number or' }).fill('84');
  await page.locator('#claim-input-dropdown span').nth(1).click();
  await page.getByText('India +').click();
  await page.getByRole('textbox', { name: 'Enter your mobile number or' }).click();
  await page.getByRole('textbox', { name: 'Enter your mobile number or' }).fill('8431980855');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('V');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('Vaishu@123');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.locator('#input-box-otp').fill('852836');
  await page.getByRole('button', { name: 'Submit code' }).click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('button', { name: 'Submit' }).first().click();
  await page.locator('#sw-gtc').getByRole('link', { name: 'Go to Cart' }).click();
});